"use strict";

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const css = require("css-tree");
const { styleLinks } = require("../lib/style-delivery");
const root = path.join(__dirname, "..");
const check = process.argv.includes("--check");
const pages = ["index.html", ...fs.readdirSync(path.join(root, "public")).filter(n => n.endsWith(".html")).map(n => `public/${n}`), "labs/lens-score/index.html", "routes/stock-landing.js"];
const manifest = {};
const compiled = new Map();

function compile(url) {
  if (compiled.has(url)) return compiled.get(url);
  const file = url.startsWith("/lens-score/assets/")
    ? path.join(root, "labs/lens-score", url.slice("/lens-score/assets/".length))
    : path.join(root, "public", url);
  const tree = css.parse(fs.readFileSync(file, "utf8"));
  css.walk(tree, node => {
    if (node.type === "Url" && !/^(?:[a-z]+:|\/|#)/i.test(node.value)) {
      node.value = path.posix.normalize(path.posix.join(path.posix.dirname(url), node.value));
    }
  });
  const result = css.generate(tree);
  compiled.set(url, result);
  return result;
}
function output(file, content) {
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) {
      throw new Error(`Styles are out of date: ${path.relative(root, file)}. Run npm run build:styles.`);
    }
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
}
for (const page of pages) {
  const links = styleLinks(fs.readFileSync(path.join(root, page), "utf8"));
  if (links.length < 2) continue;
  const key = links.map(link => link.href).join("|");
  if (manifest[key]) continue;
  const id = crypto.createHash("sha256").update(key).digest("hex").slice(0, 12);
  const url = `/bundles/site-${id}.css`;
  // Important declarations in the first layer win over legacy specificity.
  // Existing styles retain their exact relative order inside a single layer.
  const content = "/* Generated by npm run build:styles; edit the source stylesheets. */\n" +
    "@layer premium,heritage;@layer heritage{" + links.map(link => compile(link.href)).join("\n") +
    "}@layer premium{" + compile("/research-premium.css") + "}\n";
  output(path.join(root, "public", url), content);
  manifest[key] = url;
}
output(path.join(root, "lib/style-bundles.json"), JSON.stringify(manifest, null, 2) + "\n");
console.log(`${check ? "Verified" : "Built"} ${Object.keys(manifest).length} stylesheet bundles for ${pages.length} pages.`);
