/* Regenerate il-fonts.css as a SHIPPABLE set.
 *
 * The vendored font tree is 219 woff2 files across 6 families and 4 subsets,
 * none of it committed to the repo. Shipping all of it is unnecessary: the
 * design system consolidates to three faces, and woff2 alone covers every
 * browser released since 2016.
 *
 * Kept: Plus Jakarta Sans (UI + prose), JetBrains Mono (all figures),
 * Instrument Serif (wordmark only), latin + latin-ext, woff2 only.
 * DM Sans / DM Mono / Space Grotesk are aliased to the system faces in CSS
 * instead of being shipped — they were leftovers from the previous type system.
 */
const fs = require('fs');
const path = require('path');
const ROOT = '/root/work/public/vendor/fonts';
const OUT_LIST = '/tmp/fontfiles.txt';

function rangesFor(family) {
  const css = fs.readFileSync(path.join(ROOT, family + '.css'), 'utf8');
  const map = {};
  /* Anchor on the known slug. A greedy [a-z0-9-]+ swallows the slug itself, so
     "plus-jakarta-sans-latin-ext-400-normal" yields the subset "ext" and
     latin-ext silently never ships. */
  const re = new RegExp('\\/\\*\\s*' + family + '-([a-z-]+?)-\\d+-normal\\s*\\*\\/\\s*@font-face\\s*\\{[\\s\\S]*?unicode-range:\\s*([^;]+);', 'g');
  let m; while ((m = re.exec(css))) map[m[1]] = m[2].trim();
  return map;
}

const SUBSETS = ['latin', 'latin-ext'];
const FAMILIES = {
  'plus-jakarta-sans': { name: 'Plus Jakarta Sans', weights: [400, 500, 600, 700, 800], italics: [400, 600] },
  'jetbrains-mono':    { name: 'JetBrains Mono',    weights: [400, 500, 600, 700],      italics: [] },
  'instrument-serif':  { name: 'Instrument Serif',  weights: [400],                     italics: [400] }
};

let out = `/* ═══════════════════════════════════════════════════════════════════════
   Self-hosted webfonts — generated by scripts/gen-fonts.js, do not hand-edit.

   Replaces the runtime dependency on fonts.googleapis.com, which sat on the
   critical render path with display=swap: every cold visit painted in the
   system fallback and reflowed when the CDN answered.

   Scope is deliberate. The vendored tree carries 219 woff2 files across six
   families and four subsets; this ships three families, latin + latin-ext,
   woff2 only. woff2 covers every browser from 2016 onward, and the design
   system uses three faces — one sans, one mono, one serif for the wordmark.

   Every weight referenced by the stylesheets is declared. Declaring only 400
   (as the previous vendored CSS did) would make the browser synthesise every
   bold on the site.
   ═══════════════════════════════════════════════════════════════════════ */

`;

const files = [];
let n = 0;
for (const [slug, cfg] of Object.entries(FAMILIES)) {
  const dir = path.join(ROOT, slug + '-files');
  const present = new Set(fs.readdirSync(dir));
  const ranges = rangesFor(slug);
  out += `\n/* ── ${cfg.name} ─────────────────────────────────────────── */\n`;
  for (const style of ['normal', 'italic']) {
    for (const w of (style === 'normal' ? cfg.weights : cfg.italics)) {
      for (const sub of SUBSETS) {
        const base = `${slug}-${sub}-${w}-${style}`;
        if (!present.has(base + '.woff2') || !ranges[sub]) continue;
        out += `@font-face{font-family:'${cfg.name}';font-style:${style};font-weight:${w};font-display:swap;`
             + `src:url(./${slug}-files/${base}.woff2) format('woff2');unicode-range:${ranges[sub]};}\n`;
        files.push(`public/vendor/fonts/${slug}-files/${base}.woff2`);
        n++;
      }
    }
  }
}

out += `
/* The previous type system left DM Sans, DM Mono and Space Grotesk referenced
   in older stylesheets. Rather than ship three more families for a handful of
   elements, they alias onto the system faces. Anything still asking for them
   renders in the face it should have been using. */
@font-face{font-family:'DM Sans';font-style:normal;font-weight:400 700;font-display:swap;
  src:url(./plus-jakarta-sans-files/plus-jakarta-sans-latin-400-normal.woff2) format('woff2');}
@font-face{font-family:'Space Grotesk';font-style:normal;font-weight:400 700;font-display:swap;
  src:url(./plus-jakarta-sans-files/plus-jakarta-sans-latin-600-normal.woff2) format('woff2');}
@font-face{font-family:'DM Mono';font-style:normal;font-weight:400 500;font-display:swap;
  src:url(./jetbrains-mono-files/jetbrains-mono-latin-400-normal.woff2) format('woff2');}
`;

fs.writeFileSync(path.join(ROOT, 'il-fonts.css'), out);
files.push('public/vendor/tabler-icons.min.css', 'public/vendor/fonts/tabler-icons.woff2');
fs.writeFileSync(OUT_LIST, files.join('\n'));
console.log('faces declared:', n);
console.log('files to ship:', files.length);
console.log('css bytes:', fs.statSync(path.join(ROOT, 'il-fonts.css')).size);
